### ISSUE TITLE
getweb doesn't work

### ISSUE THREAD

**Issue by trbtm** [koenkooi/foo2zjs#5]
I am on Raspberry Pi OS (latest version from March 2021). I cloned this repo, ran `make` and then:

````
$ ./getweb 1020
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try wget --help for more options.
getweb: Couldn't download /
$
````

Maybe this issue is related to #2 and #3 ?

**Comment by trbtm** [comment]
I just discovered that all files/driver from getweb are already included in this repo.

**Comment by yahyayildirim** [comment]
What we can do? my printer not working. Because ./get web doesn't work. Please tell me this solutions
