### ISSUE TITLE
Website returns 403 Forbidden/404 Not Found

### ISSUE THREAD

**Issue by Devnol** [koenkooi/foo2zjs#6]
Trying to access http://foo2zjs.rkkda.com/ and http://foo2zjs.rkkda.com/foo2zjs.tar.gz return 403 Forbidden and 404 Not Found respectively

**Comment by PaperLawyer** [comment]
Same issue here.

**Comment by PaperLawyer** [comment]
Just found the solution: https://askubuntu.com/questions/1345155/how-to-install-foo2zjs-tar-gz-when-website-doesnt-work

**Comment by Devnol** [comment]
alright that works I suppose.
